## What is NumPy?
Multi-dimensional array library

## Why use Numpy over List?
NumPy is faster than list as:
1. Use fixed type:
- Uses a fixed type so faster to read less bytes of memory
- No type checking when iterating through objects

2. Contiguous memory
- In list all the datas are scattered in memory, however NumPy stores  data in one continuous block of memory.
  Why Contiguous memory is faster?
  - The computer can grab a bunch of data at once if it’s all together.
  - No need to jump around to different memory spots.
  - Math operations can use special CPU tricks (called vectorization) that only work on this kind of data.

In [2]:
# Importing library

import numpy as np

## The Basics

In [3]:
a= np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b= np.array([[9.0, 8.0, 7.0],[6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get dimension
a.ndim
b.ndim

2

In [6]:
# Get shape
b.shape

(2, 3)

In [7]:
# Get size
a.dtype

dtype('int64')

## Accessing/Changing specific elements, rows, columns

In [8]:
a= np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [9]:
# Get a specific element [r, c]
a[1, 5]

np.int64(13)

In [10]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
# Getting a specific column
a[:, 2]

array([ 3, 10])

In [12]:
# [startindex: endindex: stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [13]:
a[1, 6]= 60
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 60]]


In [14]:
a[:, 2]= [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 60]]


## Initializing Different Types of Arrays

In [15]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# any other number
np.full((2,2), 99)   # np.full((shape), number u want)

array([[99, 99],
       [99, 99]])

In [17]:
# random decimal numbers
np.random.rand(4,2)

array([[0.71746899, 0.74885365],
       [0.19390728, 0.49379122],
       [0.53673362, 0.40617492],
       [0.90387903, 0.0893676 ]])

In [19]:
# random int values
np.random.randint(7, size=(3,3))

array([[6, 3, 3],
       [6, 0, 0],
       [3, 4, 6]], dtype=int32)

In [20]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# repeat the array
arr= np.array([[1,2,3]])
r1=np.repeat(arr, 3, axis= 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [24]:
output= np.ones((5,5))
print(output)

z=np.zeros((3,3))  # 3 by 3 matrix of 0 create
z[1,1] = 9        # on 1,1, position of that matrix keeps 9
print(z)

output[1:4, 1:4]= z  # or [1:-1, 1:-1]
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
# copying arrays
a= np.array([1,2,3])
b= a.copy()
b[0]= 100

print(b)
print(a)

[100   2   3]
[1 2 3]


In [29]:
# questions:
output= np.zeros((7,7))
print(output)

z= np.ones((5,5))
z[2,2]= 5
print(z)

output[1:-1, 1:-1]= z
print(output)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 5. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## Mathematics

In [30]:
a= np.array([1,2,2,3,4])
print(a)

[1 2 2 3 4]


In [33]:
a+2

array([3, 4, 4, 5, 6])

## Linear Algebra

In [35]:
a= np.ones((2,3))
print(a)

b= np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [36]:
# find determinant
c= np.identity(3)
np.linalg.det(c)

np.float64(1.0)

## Statistics

In [37]:
stats= np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.min(stats)

np.int64(1)

In [39]:
np.max(stats)

np.int64(6)

In [41]:
np.max(stats, axis=1)

array([3, 6])

In [42]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [43]:
np.sum(stats, axis=1)

array([ 6, 15])

## Reorganizing Arrays

In [45]:
before= np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after= before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [46]:
# Vertically stacking vectors
v1= np.array([1,2,3,4])
v2= np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [47]:
# Horizontal stacking vectors
h1= np.ones((2,4))
h2= np.zeros((2,2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])